<?php
/** @var \tr33m4n\GoogleOauthMail\Block\Adminhtml\System\Config\Authenticate $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
$ajaxUrl = $block->escapeJs($block->getData('ajax_url'));
$errorMessage = $block->escapeJs($block->escapeHtml(__('Error trying to authenticate with Google!')));

$scriptString = <<<script
require(['prototype'], function() {

//<![CDATA[
    function validateVat() {
        var validationMessage = $('validation_result');

        params = {
            client_id: $('tr33m4n_google_oauth_mail_authentication_client_id').value,
            client_secret: $('tr33m4n_google_oauth_mail_authentication_client_secret').value
        };

        new Ajax.Request('{$ajaxUrl}', {
            parameters: params,
            onSuccess: function(response) {
                var result = '{$errorMessage}';

                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.valid == 1) {
                        validationMessage.removeClassName('hidden').removeClassName('admin__field-error').
                        addClassName('note');
                        validationMessage.setStyle({color:'green'});
                    } else {
                        validationMessage.removeClassName('hidden').addClassName('admin__field-error');
                    }
                } catch (e) {
                    validationMessage.removeClassName('hidden').addClassName('admin__field-error');
                }
                validationMessage.update(result);
            }
        });
    }

    window.validateVat = validateVat;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-authenticate">
    <p class="admin__field-error hidden" id="validation_result"></p>
    <button class="action-authenticate" type="button" id="<?= /* @noEscape */ $block->getData('html_id') ?>">
        <span><?= $block->escapeHtml($block->getData('button_label')) ?></span>
    </button>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#validation_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'validateVat();event.preventDefault();',
    '#' . /* @noEscape */ $block->getData('html_id')
); ?>
